general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando para bloquear
    before_sleep_cmd = loginctl lock-session    # Bloquear antes de que el PC se duerma
    after_sleep_cmd = hyprctl dispatch dpms on  # Asegurar que la pantalla encienda al volver
}

# 1. BAJAR BRILLO (Tras 5 minutos de inactividad)
listener {
    timeout = 300                              
    on-timeout = brightnessctl set 10%          # Baja el brillo al 10%
    on-resume = brightnessctl set 100%          # RESTAURA el brillo al volver
}

# 2. BLOQUEAR (Tras 5 minutos de inactividad)
listener {
    timeout = 600                                
    on-timeout = loginctl lock-session          # Lanza hyprlock
}

# 3. SUSPENDER (Tras 30 minutos de inactividad)
listener {
    timeout = 3600                               
    on-timeout = systemctl suspend              # Suspensión a RAM (No apaga el PC)
}
