# VARIABLES
$wall = /home/rafaelbc/Pictures/Wallpapers/gepardoDark.jpg

# BACKGROUND
background {
    monitor =
    path = $wall
    blur_passes = 0 
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

# PANEL LATERAL 
BI = % del PEM          (Beneficio Industrial)
CT = PEM + GG + BI    (Coste Total) -> ￼￼antes de impuestos
shape {
    monitor =
    size = 480, 100% 
    color = rgba(255, 255, 255, 0.04)
    rounding = 0
    border_size = 1
    border_color = rgba(255, 255, 255, 0.08)
    
    position = 0, 0
    halign = left
    valign = center
}

# HORA (Grande y limpia)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgb(255, 255, 255)
    font_size = 90
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 50, 150
    halign = left
    valign = center
}

# FECHA (En español)
label {
    monitor =
    text = cmd[update:1000] echo "$(LC_TIME=es_ES.UTF-8 date +"%A, %d de %B")"
    color = rgba(255, 255, 255, 0.7)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 55, 220
    halign = left
    valign = center
}

# CAMPO DE CONTRASEÑA 
input-field {
    monitor =
    size = 320, 50
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(0, 0, 0, 0.3) 
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <span foreground="##ffffffaa">Password...</span>
    hide_input = false
    position = 50, -80
    halign = left
    valign = center
}


